### ISSUE TITLE
emails used to come from Contractors Database in outlook inbox, now they come from Mark Tiderman

### ISSUE THREAD

**Issue by marktiderman** [StreamlinedStudio/Contractors-React#27]
[Task](https://app.trackduck.com/project/5a68baa202525bf44423a3f8/issue/5a68d3ac8c44ffa149914dd8?utm_source=integration&utm_medium=app_github&utm_content=task) with ***Low*** priority was created by ***Bryan Comstock***:

>emails used to come from Contractors Database in outlook inbox, now they come from Mark Tiderman

[![Issue screenshot](https://app.trackduck.com/file/crop/5a68baa202525bf44423a3f8-1516819372056-300-150.jpg?utm_source=integration&utm_medium=app_github&utm_content=preview)](https://app.trackduck.com/preview/awsi/5a68baa202525bf44423a3f8-1516819372056-300-150.jpg?utm_source=integration&utm_medium=app_github&utm_content=preview)

Environment: ***Chrome 62*** on ***Windows*** with ***1920x925*** screen size.

Check it in your [website](https://pgone.sharepoint.com/sites/contractors/home/alpha/default.aspx?tdtask=5a68d3ac8c44ffa149914dd8) or get [more details...](https://app.trackduck.com/project/5a68baa202525bf44423a3f8/issue/5a68d3ac8c44ffa149914dd8?utm_source=integration&utm_medium=app_github&utm_content=task)

**Comment by kdipaolo** [comment]
@marktiderman Would you mind helping me out with this?
I tried adding bryan's pg email in the send as column but it doesnt seem to work as in the email doesnt get sent out when I do a test request.  Heres where you add the send as: http://share.streamlinedstudio.com/3M1Y290v2H1E
